### ISSUE TITLE
Join the Organisation!

### ISSUE THREAD

**Issue by siriuswapnil** [codesocbitd/beginners-welcome#1]
Welcome BITD junta! Join in the fun. Follow the steps written in readme.md to submit your details. Once, you join your profiles will be visible on the homepage, of the coding society website.  Happy Hacktoberfest!

**Comment by bharati-21** [comment]
Would like to know more about contributing! Checked readme.md and didn't have any steps! Can you please fill in?

**Comment by siriuswapnil** [comment]
Sorry @bharati-21 bro, we've not started yet. Keep hustling!
